"""Export the verified latest-M0 Power figures for report 2.8."""
from pathlib import Path
import sys, json, hashlib
POWER=next(parent for parent in Path(__file__).resolve().parents
           if parent.name == 'power scalability' and (parent/'DATA').is_dir())
ROOT=POWER.parent; SCRIPTS=POWER/'script/Main/figures'
sys.path.insert(0,str(SCRIPTS))
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib.text import Text
from matplotlib.collections import PathCollection
import numpy as np
import power_m0_preview_figures_20260907 as pf
import power_retest_figures as prior
import power_revision_figures as old
import power_m0_preview_drop_20260907 as grouped

REPORT=ROOT/'Imperial College Individual Project Template_LaTeX'
INPUT=POWER/'DATA/analysis/current/report_v2_8_analysis'
OUT=POWER/'DATA/analysis/current/report_v2_8_figures'
REPORT_OUT=REPORT/'figures/power/v2_8'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def export(fig,out,stem,description,semantics):
    assert Path(out).resolve()==OUT.resolve()
    if stem=='branch_current_balance':
        fig.subplots_adjust(bottom=.15)
        for module,ax in zip(pf.MODULES,fig.axes):
            for load in pf.LOADS:
                for n in range(1,5):
                    rows=sorted((b for b in pf.ALL_BRANCHES if b['module_id']==module and b['load']==load and b['N']==n),key=lambda b:b['combo'])
                    xx=n+(-.10 if load=='ZERO' else .10)+(np.linspace(-.045,.045,len(rows)) if len(rows)>1 else np.array([0.]))
                    for row,x in zip(rows,xx):
                        if pf.key(row) in pf.TARGETS:ax.scatter(x,row['I_recorded_mA'],marker='*',s=67,color=pf.COLORS[load],edgecolors=pf.DARK_CHARCOAL,linewidths=.5,zorder=7)
    if stem=='single_module_screening':
        ax=fig.axes[0]
        for load,x in [('ZERO',0.),('MAX',.15)]:
            row,=[r for r in pf.ALL_RUNS if r['combo']=='M0' and r['load']==load]
            ax.scatter(x,row['I_sum_mA'],marker='*',s=78,color=pf.COLORS[load],edgecolors=pf.DARK_CHARCOAL,linewidths=.5,zorder=7)
    for artist in list(fig.texts):
        if 'preview' in artist.get_text().lower():artist.remove()
    # Keep report exports compatible with the PDF workflow: ASCII hyphens in
    # all plotted text, including signs generated by Matplotlib formatters.
    fig.canvas.draw()
    for artist in fig.findobj(Text):
        artist.set_text(artist.get_text().translate(str.maketrans({'−':'-','–':'-','—':'-'})))
    if stem=='module_voltage_drop':
        fig.set_size_inches(200/25.4,150/25.4)
    fig.canvas.draw();renderer=fig.canvas.get_renderer();outside=[]
    for artist in fig.findobj(matplotlib.text.Text):
        if artist.get_visible() and artist.get_text().strip():
            bb=artist.get_window_extent(renderer)
            if bb.x0<fig.bbox.x0-1 or bb.x1>fig.bbox.x1+1 or bb.y0<fig.bbox.y0-1 or bb.y1>fig.bbox.y1+1:outside.append(artist.get_text())
    assert not outside,(stem,outside)
    files=[]
    for ext in ('pdf','png','svg'):
        p=OUT/f'{stem}.{ext}'
        metadata={'Title':stem,'Description':'Report 2.8 Power figure'} if ext=='svg' else {'Title':stem,'Subject':'Report 2.8 Power figure'}
        fig.savefig(p,dpi=300,bbox_inches=None,facecolor='white',metadata=metadata)
        files.append({'name':p.name,'sha256':sha(p),'bytes':p.stat().st_size})
    plt.close(fig)
    return {'stem':stem,'description':description,'semantics':semantics,'files':files,'dimensions_mm':[round(x*25.4,2) for x in fig.get_size_inches()]}
def export_group(fig,stem,description):return export(fig,OUT,stem,description,{'spread':'Combination SD only; no complete repeat added'})
def main():
    assert not OUT.exists() and not REPORT_OUT.exists();OUT.mkdir();REPORT_OUT.mkdir(parents=True)
    pf.INPUT=INPUT;pf.OUTPUT=OUT;prior.INPUT=INPUT;prior.export=export;old.export=export;pf.export=export
    runs,branches,predictions=prior.normalized_data();pf.ALL_RUNS,pf.ALL_BRANCHES=runs,branches
    legacy=json.loads(prior.LEGACY.read_text(encoding='utf-8-sig'))
    blocked=[r for r in legacy['runs'] if r['N']==1 and r['frequency_hz']==200 and r['protocol_mode']=='FULL' and r['load']=='ZERO' and r['state']==old.BLOCKED]
    with plt.style.context(pf.STYLE),matplotlib.rc_context(pf.PUBLICATION_STYLE):
        matplotlib.rcParams.update({'pdf.fonttype':42,'ps.fonttype':42,'svg.fonttype':'none','svg.hashsalt':'eskin-power-v2.8','axes.unicode_minus':False})
        figs=[pf.plot_scaling(runs),pf.plot_voltage(runs,branches),pf.plot_drop(runs,branches),old.plot_screening(blocked+runs,OUT),old.plot_branches(branches,OUT),old.plot_temperature(runs,branches,OUT),prior.plot_prediction(predictions,OUT)]
    grouped.DATA=INPUT;grouped.OUT=OUT;grouped.export=export_group
    branches2,groups,checks=grouped.collect()
    with plt.style.context(pf.STYLE),matplotlib.rc_context(pf.PUBLICATION_STYLE):
        matplotlib.rcParams.update({'axes.unicode_minus':False})
        figs.append(grouped.four(branches2,checks))
    for entry in figs:
        for item in entry['files']:
            src=OUT/item['name'];dst=REPORT_OUT/item['name'];shutil.copy2(src,dst);assert sha(dst)==item['sha256']
    inputs=[INPUT/name for name in ('configuration_summary.csv','branch_readings.csv','group_summary.csv','additivity_checks.csv','load_voltage_drop_changes.csv')]
    manifest={'version':'2.8','figures':figs,'inputs':[{'path':str(p),'sha256':sha(p)} for p in inputs],
      'scripts':[{'path':str(p),'sha256':sha(p)} for p in [Path(__file__),Path(pf.__file__),Path(prior.__file__),Path(old.__file__),Path(grouped.__file__)]],
      'counts':{'active_report_figures':8,'conditions':30,'branches':64,'load_difference_pairs':32,'targeted_branch_updates':7,'new_complete_repeats':0},
      'review':'Machine checks only; human scientific verification pending'}
    (OUT/'figure_manifest.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
    shutil.copy2(OUT/'figure_manifest.json',REPORT_OUT/'figure_manifest.json')
    print(json.dumps({'figures':len(figs),'output':str(REPORT_OUT)},indent=2))
if __name__=='__main__':
    import shutil
    main()
